name: mobiledev_wan
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  firebase_core: ^3.15.2
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.2.10
  firebase_storage: ^12.3.3
  image_picker: ^1.1.1
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.0
  intl: ^0.18.1
  permission_handler: ^11.3.1
  android_alarm_manager_plus: ^4.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/sounds/alarm.mp3

flutter_launcher_icons:
  android: true
  image_path: "assets/app_icon.png"

