// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClOtTHUlnqDfZdnuV9hLn7APbjH-cvkZA',
    appId: '1:337843740365:web:f07f52285584dfc6ab1384',
    messagingSenderId: '337843740365',
    projectId: 'dbmobileapp-1f398',
    authDomain: 'dbmobileapp-1f398.firebaseapp.com',
    storageBucket: 'dbmobileapp-1f398.firebasestorage.app',
    measurementId: 'G-JYGHZMCXNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSbDtjT2x-x8FchnGJgDHc8aIZNvfXWfA',
    appId: '1:337843740365:android:8523af6ac98c107dab1384',
    messagingSenderId: '337843740365',
    projectId: 'dbmobileapp-1f398',
    storageBucket: 'dbmobileapp-1f398.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiYAMNUcvp6BiDYs93sz3n6yEUBymq8_g',
    appId: '1:337843740365:ios:bdd042e7c8f81c5eab1384',
    messagingSenderId: '337843740365',
    projectId: 'dbmobileapp-1f398',
    storageBucket: 'dbmobileapp-1f398.firebasestorage.app',
    iosBundleId: 'com.example.mobiledevWan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiYAMNUcvp6BiDYs93sz3n6yEUBymq8_g',
    appId: '1:337843740365:ios:bdd042e7c8f81c5eab1384',
    messagingSenderId: '337843740365',
    projectId: 'dbmobileapp-1f398',
    storageBucket: 'dbmobileapp-1f398.firebasestorage.app',
    iosBundleId: 'com.example.mobiledevWan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClOtTHUlnqDfZdnuV9hLn7APbjH-cvkZA',
    appId: '1:337843740365:web:44774b3202886d7dab1384',
    messagingSenderId: '337843740365',
    projectId: 'dbmobileapp-1f398',
    authDomain: 'dbmobileapp-1f398.firebaseapp.com',
    storageBucket: 'dbmobileapp-1f398.firebasestorage.app',
    measurementId: 'G-481GWC0Y96',
  );
}
